services:
  main-app:
    container_name: main-app
    build:
      context: ..
      dockerfile: Dockerfile
    command: "uvicorn --factory application.api.main:create_app --reload --host 0.0.0.0 --port 8000"
    ports:
      - '${API_PORT}:8000'
    volumes:
      - ../app/:/app
    env_file:
      - ../.env
    networks:
      - backend
  celery-worker:
    container_name: celery-worker
    build:
      context: ..
      dockerfile: Dockerfile
    command: >
      celery -A infrastructure.task_queue.init worker --loglevel=info
    depends_on:
      - redis
    env_file:
      - ../.env
    networks:
      - backend

networks:
  backend:
    driver: bridge
