version: '3.9'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - auth_service_app
      - weather_service_app
      - static_service_app

    networks:
      - backend

networks:
  backend:
    driver: bridge